// Sample/Angular/sample-sdk-video-call/src/app/video-call/video-call.component.ts
import { Component, OnInit } from '@angular/core';
import { ConfigVideoCall } from '../ConfigVideoCall';
import * as VideoCallSDK from 'video-call-js-sdk';

declare var JitsiMeetExternalAPI: any;
// declare function VideoCall(): any;
// const VideoCallSDK = VideoCall();

@Component({
    selector: 'app-video-call',
    templateUrl: './video-call.component.html',
    styleUrls: ['./video-call.component.css'],
})
export class VideoCallComponent implements OnInit {
    api: any;
    imageCapture: any;
    video;

    constructor() {}
    ngOnInit(): void {
        this.video = VideoCallSDK.initConfig(null, ConfigVideoCall);
        this.api = this.video.initVideoCall(
            JitsiMeetExternalAPI,
            localStorage.getItem('uuidAdmin').replace(/"/g, ''),
            '100%',
            590
        );
    }

    capture() {
        this.video.capture((base64) => {
            console.log(base64);
            this.imageCapture = base64;
        });
    }
}

// Sample/ReactJS/react-fcm/src/VideoCallComponent.js
import React, { useEffect, useState, useRef } from 'react';
import { ConfigVideoCall } from './ConfigVideoCall';
import * as VideoCall from 'video-call-js-sdk';

const VideoCallComponent = (props) => {
    const video = VideoCall.initConfig('call', ConfigVideoCall);
    const [imageCapture, setImageCapture] = useState(null);

    useEffect(() => {
        video.initVideoCall(
            window.JitsiMeetExternalAPI,
            localStorage.getItem('uuidAdmin').replace(/"/g, ''),
            '100%',
            590
        );
    }, []);

    function capture() {
        video.capture((base64) => {
            console.log(base64);
            setImageCapture(base64);
        });
    }
    return (
        <div>
            <div id="meet"></div>
            <button
                width="100%"
                class="btn btn-primary d-inline-flex"
                onClick={() => capture()}
            >
                Chụp màn hình
            </button>
            <div class="images mt-2">
                <div>
                    <img src={imageCapture} width="100%" alt="" />
                </div>
            </div>
        </div>
    );
};

export default VideoCallComponent;
